# Generated by Django 4.1.6 on 2023-02-13 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.TextField(default=datetime.datetime(2023, 2, 13, 10, 42, 32, 749416, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
