# Generated by Django 4.1.6 on 2023-02-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_drone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drone',
        ),
    ]
