# Generated by Django 4.1.6 on 2023-02-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_drone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drone',
        ),
    ]
