# Generated by Django 4.1.6 on 2023-02-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_drone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(blank=True, max_length=122),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='proj',
            field=models.CharField(blank=True, choices=[('drone', 'Drone_detection'), ('pothole', 'Pothole_counter'), ('facemask', 'Facemask_detection'), ('tooth', 'tooth_detection')], max_length=100),
        ),
    ]
